### ISSUE TITLE
Bloating - git history included in release package

### ISSUE THREAD

**Issue by babhishek21** [osava-nsit/osava#1]
Your release package (for Windows, available [here](https://github.com/osava-nsit/osava/releases))  includes the `.git` folder - the one that contains all your git revision history as well as project level configs. For example, it is clear that you began work in this [Bitbucket repo.](https://bitbucket.org/uditarora/osask). 

The release package does not need your source history to function. Consider removing it.

**Comment by uditarora** [comment]
Thanks for pointing this out. Fixed.
